/*
 * Copyright (c) 2018. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
 * Morbi non lorem porttitor neque feugiat blandit. Ut vitae ipsum eget quam lacinia accumsan.
 * Etiam sed turpis ac ipsum condimentum fringilla. Maecenas magna.
 * Proin dapibus sapien vel ante. Aliquam erat volutpat. Pellentesque sagittis ligula eget metus.
 * Vestibulum commodo. Ut rhoncus gravida arcu.
 */

package com.openweather.challenge.openweatherapp.entity;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;
import android.arch.persistence.room.Room;
import android.os.Parcel;
import android.os.Parcelable;


/**
 * Created by manuel on 21,August,2018
 */

/**
 * Defines the schema of a table in {@link Room} for a single weather
 * forecast. The date is used as an {@link Index} so that its uniqueness can be ensured. Indexes
 * also allow for fast lookup for the column.
 */
@Entity(tableName = "weather_table", indices = {@Index(value = {"dt"}, unique = true)})
public class WeatherEntity implements Parcelable {

    /**
     * Makes sure the id is the primary key (ensures uniqueness), is auto generated by {@link Room}.
     */
    @PrimaryKey(autoGenerate = true)
    private int id;
    private double lat;
    private double lon;
    private int weather_id;
    private String weather_main;
    private String weather_description;
    private String weather_icon;
    private String base;
    private double main_temp;
    private int main_pressure;
    private int main_humidity;
    private double main_temp_min;
    private double main_temp_max;
    private int visibility;
    private double wind_speed;
    private int wind_deg;
    private int clouds;
    private long dt;
    private int sys_type;
    private int sys_id;
    private double sys_message;
    private String sys_country;
    private long sys_sunrise;
    private long sys_sunset;
    private String name;
    private int cod;

    public WeatherEntity(int id, double lat, double lon, int weather_id, String weather_main, String weather_description,
                         String weather_icon, String base, double main_temp, int main_pressure, int main_humidity, double main_temp_min,
                         double main_temp_max, int visibility, double wind_speed, int wind_deg, int clouds, long dt, int sys_type, int sys_id,
                         double sys_message, String sys_country, long sys_sunrise, long sys_sunset, String name, int cod) {
        this.id = id;
        this.lat = lat;
        this.lon = lon;
        this.weather_id = weather_id;
        this.weather_main = weather_main;
        this.weather_description = weather_description;
        this.weather_icon = weather_icon;
        this.base = base;
        this.main_temp = main_temp;
        this.main_pressure = main_pressure;
        this.main_humidity = main_humidity;
        this.main_temp_min = main_temp_min;
        this.main_temp_max = main_temp_max;
        this.visibility = visibility;
        this.wind_speed = wind_speed;
        this.wind_deg = wind_deg;
        this.clouds = clouds;
        this.dt = dt;
        this.sys_type = sys_type;
        this.sys_id = sys_id;
        this.sys_message = sys_message;
        this.sys_country = sys_country;
        this.sys_sunrise = sys_sunrise;
        this.sys_sunset = sys_sunset;
        this.name = name;
        this.cod = cod;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public double getLat() {
        return lat;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public double getLon() {
        return lon;
    }

    public void setLon(double lon) {
        this.lon = lon;
    }

    public int getWeather_id() {
        return weather_id;
    }

    public void setWeather_id(int weather_id) {
        this.weather_id = weather_id;
    }

    public String getWeather_main() {
        return weather_main;
    }

    public void setWeather_main(String weather_main) {
        this.weather_main = weather_main;
    }

    public String getWeather_description() {
        return weather_description;
    }

    public void setWeather_description(String weather_description) {
        this.weather_description = weather_description;
    }

    public String getWeather_icon() {
        return weather_icon;
    }

    public void setWeather_icon(String weather_icon) {
        this.weather_icon = weather_icon;
    }

    public String getBase() {
        return base;
    }

    public void setBase(String base) {
        this.base = base;
    }

    public double getMain_temp() {
        return main_temp;
    }

    public void setMain_temp(double main_temp) {
        this.main_temp = main_temp;
    }

    public int getMain_pressure() {
        return main_pressure;
    }

    public void setMain_pressure(int main_pressure) {
        this.main_pressure = main_pressure;
    }

    public int getMain_humidity() {
        return main_humidity;
    }

    public void setMain_humidity(int main_humidity) {
        this.main_humidity = main_humidity;
    }

    public double getMain_temp_min() {
        return main_temp_min;
    }

    public void setMain_temp_min(double main_temp_min) {
        this.main_temp_min = main_temp_min;
    }

    public double getMain_temp_max() {
        return main_temp_max;
    }

    public void setMain_temp_max(double main_temp_max) {
        this.main_temp_max = main_temp_max;
    }

    public int getVisibility() {
        return visibility;
    }

    public void setVisibility(int visibility) {
        this.visibility = visibility;
    }

    public double getWind_speed() {
        return wind_speed;
    }

    public void setWind_speed(double wind_speed) {
        this.wind_speed = wind_speed;
    }

    public int getWind_deg() {
        return wind_deg;
    }

    public void setWind_deg(int wind_deg) {
        this.wind_deg = wind_deg;
    }

    public int getClouds() {
        return clouds;
    }

    public void setClouds(int clouds) {
        this.clouds = clouds;
    }

    public long getDt() {
        return dt;
    }

    public void setDt(long dt) {
        this.dt = dt;
    }

    public int getSys_type() {
        return sys_type;
    }

    public void setSys_type(int sys_type) {
        this.sys_type = sys_type;
    }

    public int getSys_id() {
        return sys_id;
    }

    public void setSys_id(int sys_id) {
        this.sys_id = sys_id;
    }

    public double getSys_message() {
        return sys_message;
    }

    public void setSys_message(double sys_message) {
        this.sys_message = sys_message;
    }

    public String getSys_country() {
        return sys_country;
    }

    public void setSys_country(String sys_country) {
        this.sys_country = sys_country;
    }

    public long getSys_sunrise() {
        return sys_sunrise;
    }

    public void setSys_sunrise(long sys_sunrise) {
        this.sys_sunrise = sys_sunrise;
    }

    public long getSys_sunset() {
        return sys_sunset;
    }

    public void setSys_sunset(long sys_sunset) {
        this.sys_sunset = sys_sunset;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getCod() {
        return cod;
    }

    public void setCod(int cod) {
        this.cod = cod;
    }

    @Override
    public String toString() {
        return "WeatherEntity{" +
                "id=" + id +
                ", lat=" + lat +
                ", lon=" + lon +
                ", weather_id=" + weather_id +
                ", weather_main='" + weather_main + '\'' +
                ", weather_description='" + weather_description + '\'' +
                ", weather_icon='" + weather_icon + '\'' +
                ", base='" + base + '\'' +
                ", main_temp=" + main_temp +
                ", main_pressure=" + main_pressure +
                ", main_humidity=" + main_humidity +
                ", main_temp_min=" + main_temp_min +
                ", main_temp_max=" + main_temp_max +
                ", visibility=" + visibility +
                ", wind_speed=" + wind_speed +
                ", wind_deg=" + wind_deg +
                ", clouds=" + clouds +
                ", dt=" + dt +
                ", sys_type=" + sys_type +
                ", sys_id=" + sys_id +
                ", sys_message=" + sys_message +
                ", sys_country='" + sys_country + '\'' +
                ", sys_sunrise=" + sys_sunrise +
                ", sys_sunset=" + sys_sunset +
                ", name='" + name + '\'' +
                ", cod=" + cod +
                '}';
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {

    }
}
